import { Category, Product, Seller, User, ProductCategory, Review, Order, Offer, Conversation } from "./types"

export const mockSellers: Seller[] = [
  {
    id: "seller-1",
    email: "raj.guitars@example.com",
    name: "Rajesh Kumar",
    role: "seller",
    shopName: "Raj Guitars & More",
    avatar: "https://i.pravatar.cc/150?img=11",
    location: "Mumbai, MH",
    verified: true,
    verificationStatus: "verified",
    rating: 4.8,
    totalSales: 342,
    createdAt: "2023-01-15",
    bio: "Professional musician and luthier with 15 years experience."
  },
  {
    id: "seller-2",
    email: "ananya.music@example.com",
    name: "Ananya Singh",
    role: "seller",
    shopName: "Melody House",
    avatar: "https://i.pravatar.cc/150?img=5",
    location: "Bangalore, KA",
    verified: true,
    verificationStatus: "verified",
    rating: 4.9,
    totalSales: 521,
    createdAt: "2022-08-10",
    bio: "Curated collection of keyboards and studio gear."
  },
  {
    id: "seller-3",
    email: "trad.sounds@example.com",
    name: "Vikram Patel",
    role: "seller",
    shopName: "Traditional Sounds",
    avatar: "https://i.pravatar.cc/150?img=15",
    location: "Chennai, TN",
    verified: false,
    verificationStatus: "pending",
    rating: 4.6,
    totalSales: 128,
    createdAt: "2023-05-20",
    bio: "Specializing in Indian classical instruments."
  },
  {
    id: "seller-4",
    email: "drum.world@example.com",
    name: "Arjun Mehta",
    role: "seller",
    shopName: "Drum World India",
    avatar: "https://i.pravatar.cc/150?img=8",
    location: "Delhi, DL",
    verified: true,
    verificationStatus: "verified",
    rating: 4.7,
    totalSales: 210,
    createdAt: "2023-03-12",
  },
]

export const mockCategories: Category[] = [
  { id: "1", name: "Guitars", slug: "guitars", description: "Acoustic, electric, bass guitars", image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400", productCount: 124 },
  { id: "2", name: "Keyboards / Pianos", slug: "keyboards-pianos", description: "Digital pianos, synths, MIDI controllers", image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=400", productCount: 89 },
  { id: "3", name: "Drums / Percussion", slug: "drums-percussion", description: "Acoustic drums, electronic drums, percussion", image: "https://images.unsplash.com/photo-1519892300165-cb15471532bb?w=400", productCount: 67 },
  { id: "4", name: "Violins / String Instruments", slug: "violins-string", description: "Violins, cellos, violas", image: "https://images.unsplash.com/photo-1465821185615-20b3c2fbf41b?w=400", productCount: 45 },
  { id: "5", name: "Wind Instruments", slug: "wind-instruments", description: "Saxophones, flutes, trumpets", image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=400", productCount: 38 },
  { id: "6", name: "Traditional Instruments", slug: "traditional", description: "Sitar, tabla, harmonium", image: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400", productCount: 52 },
  { id: "7", name: "Microphones / Audio Equipment", slug: "microphones-audio", description: "Mics, headphones, audio interfaces", image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400", productCount: 98 },
  { id: "8", name: "Amplifiers / Speakers", slug: "amplifiers-speakers", description: "Guitar amps, PA speakers", image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=400", productCount: 76 },
  { id: "9", name: "Studio Gear", slug: "studio-gear", description: "Mixers, interfaces, monitors", image: "https://images.unsplash.com/photo-1598488035139-bdbb22374218?w=400", productCount: 64 },
  { id: "10", name: "Accessories", slug: "accessories", description: "Strings, picks, cables, stands", image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400", productCount: 210 },
]

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Fender American Professional II Stratocaster",
    slug: "fender-american-professional-ii-stratocaster",
    category: "Guitars",
    brand: "Fender",
    model: "AM Pro II Strat",
    price: 125000,
    originalPrice: 145000,
    condition: "new",
    quantity: 3,
    location: "Mumbai, MH",
    description: "The American Professional II Stratocaster delivers exceptional tone and modern playability with timeless Fender style. Features V-Mod II single-coil pickups, deep C neck profile, and 2-point tremolo with cold-rolled steel block.",
    specifications: {
      "Body": "Alder",
      "Neck": "Maple, Deep C",
      "Fingerboard": "Rosewood",
      "Pickups": "V-Mod II Single-Coil",
      "Bridge": "2-Point Tremolo",
      "Frets": "22 Narrow Tall",
      "Scale Length": "25.5\"",
      "Weight": "3.6 kg"
    },
    images: [
      "https://images.unsplash.com/photo-1558098329-a11cff621064?w=800",
      "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800",
      "https://images.unsplash.com/photo-1498032786690-39352d6d611e?w=800"
    ],
    rating: 4.8,
    reviewCount: 24,
    sellerId: "seller-1",
    seller: mockSellers[0],
    createdAt: "2024-11-10",
    updatedAt: "2024-11-10",
    isApproved: true,
    isFeatured: true,
  },
  {
    id: "prod-2",
    name: "Yamaha P-125 Digital Piano - Black",
    slug: "yamaha-p-125-digital-piano",
    category: "Keyboards / Pianos",
    brand: "Yamaha",
    model: "P-125",
    price: 52000,
    condition: "new",
    quantity: 8,
    location: "Bangalore, KA",
    description: "Compact and powerful digital piano with Graded Hammer Standard keyboard and Pure CF Sound Engine. Perfect for beginners and intermediate players.",
    specifications: {
      "Keys": "88 GHS Weighted",
      "Polyphony": "192 notes",
      "Voices": "24",
      "Connectivity": "USB, Headphone, Aux",
      "Speakers": "2x 7W",
      "Dimensions": "1326 x 295 x 166 mm",
      "Weight": "11.8 kg"
    },
    images: [
      "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800",
      "https://images.unsplash.com/photo-1552422535-c45813c61732?w=800",
    ],
    rating: 4.7,
    reviewCount: 56,
    sellerId: "seller-2",
    seller: mockSellers[1],
    createdAt: "2024-11-08",
    updatedAt: "2024-11-08",
    isApproved: true,
    isFeatured: true,
  },
  {
    id: "prod-3",
    name: "Pearl Export EXX Drum Kit - 5 Piece",
    slug: "pearl-export-exx-drum-kit",
    category: "Drums / Percussion",
    brand: "Pearl",
    model: "EXX705NBR",
    price: 68000,
    condition: "used",
    quantity: 1,
    location: "Delhi, DL",
    description: "Well maintained Pearl Export kit, 2 years old. Poplar and Asian Mahogany shells. Includes hardware but no cymbals. Minor stick marks but structurally excellent.",
    specifications: {
      "Shells": "Poplar/Asian Mahogany",
      "Sizes": "22x18, 10x7, 12x8, 16x16, 14x5.5",
      "Hardware": "Included",
      "Cymbals": "Not included",
      "Finish": "Jet Black"
    },
    images: [
      "https://images.unsplash.com/photo-1519892300165-cb15471532bb?w=800",
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
    ],
    rating: 4.5,
    reviewCount: 12,
    sellerId: "seller-4",
    seller: mockSellers[3],
    createdAt: "2024-11-05",
    updatedAt: "2024-11-05",
    isApproved: true,
    usedCondition: {
      overall: "good",
      body: "good",
      neck: "excellent",
      strings: "fair",
      electronics: "excellent",
      cosmetic: "good",
      damageDetails: "Minor stick marks on snare, small chip on bass drum hoop",
      damageImages: ["https://images.unsplash.com/photo-1519892300165-cb15471532bb?w=400"],
      yearOfManufacture: "2022",
      modifications: "Upgraded snare wires"
    }
  },
  {
    id: "prod-4",
    name: "Stentor Student II Violin 4/4",
    slug: "stentor-student-ii-violin",
    category: "Violins / String Instruments",
    brand: "Stentor",
    model: "Student II",
    price: 18500,
    condition: "new",
    quantity: 15,
    location: "Chennai, TN",
    description: "Ideal student violin with solid carved spruce front and maple back. Includes bow, case and rosin. Hand-finished and setup in UK.",
    specifications: {
      "Size": "4/4",
      "Top": "Solid Spruce",
      "Back": "Maple",
      "Fingerboard": "Ebony",
      "Bow": "Included",
      "Case": "Lightweight case included"
    },
    images: ["https://images.unsplash.com/photo-1465821185615-20b3c2fbf41b?w=800"],
    rating: 4.6,
    reviewCount: 34,
    sellerId: "seller-3",
    seller: mockSellers[2],
    createdAt: "2024-11-01",
    updatedAt: "2024-11-01",
    isApproved: true,
  },
  {
    id: "prod-5",
    name: "Shure SM58 Dynamic Vocal Microphone",
    slug: "shure-sm58-dynamic-vocal-microphone",
    category: "Microphones / Audio Equipment",
    brand: "Shure",
    model: "SM58-LC",
    price: 9500,
    originalPrice: 11000,
    condition: "new",
    quantity: 25,
    location: "Mumbai, MH",
    description: "Industry standard vocal microphone, legendary for live performance. Cardioid pattern, tailored vocal response, rugged construction.",
    specifications: {
      "Type": "Dynamic",
      "Polar Pattern": "Cardioid",
      "Frequency": "50Hz - 15kHz",
      "Impedance": "150 Ohms",
      "Connector": "XLR",
      "Weight": "298g"
    },
    images: ["https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800"],
    rating: 4.9,
    reviewCount: 189,
    sellerId: "seller-2",
    seller: mockSellers[1],
    createdAt: "2024-10-28",
    updatedAt: "2024-10-28",
    isApproved: true,
    isFeatured: true,
  },
  {
    id: "prod-6",
    name: "Marshall DSL40CR 40W Tube Combo Amp",
    slug: "marshall-dsl40cr-tube-combo-amp",
    category: "Amplifiers / Speakers",
    brand: "Marshall",
    model: "DSL40CR",
    price: 72000,
    condition: "used",
    quantity: 1,
    location: "Bangalore, KA",
    description: "Powerful all-valve combo with classic Marshall tones. 2 channels, reverb, FX loop, emulated out. Recently serviced with new EL34s.",
    specifications: {
      "Power": "40W (20W low)",
      "Tubes": "4x ECC83, 2x EL34",
      "Speaker": "12\" Celestion V-Type",
      "Channels": "Classic & Ultra Gain",
      "Reverb": "Digital"
    },
    images: ["https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800"],
    rating: 4.7,
    reviewCount: 18,
    sellerId: "seller-1",
    seller: mockSellers[0],
    createdAt: "2024-10-20",
    updatedAt: "2024-10-20",
    isApproved: true,
    usedCondition: {
      overall: "excellent",
      body: "excellent",
      neck: "excellent",
      strings: "excellent",
      electronics: "excellent",
      cosmetic: "good",
      damageDetails: "Light tolex scuff on bottom corner",
      yearOfManufacture: "2021"
    }
  },
  {
    id: "prod-7",
    name: "Sitar - Professional Concert Grade",
    slug: "sitar-professional-concert-grade",
    category: "Traditional Instruments",
    brand: "Rikhi Ram",
    model: "Concert Pro",
    price: 45000,
    condition: "new",
    quantity: 4,
    location: "Delhi, DL",
    description: "Handcrafted concert sitar made from seasoned toon wood and gourd. Professional grade with Jawari done by master craftsman. Includes fiber case.",
    specifications: {
      "Material": "Toon Wood",
      "Strings": "7 Main + 11 Sympathetic",
      "Gourd": "Natural",
      "Frets": "20 Brass",
      "Length": "~130cm",
      "Case": "Fiber case included"
    },
    images: ["https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800"],
    rating: 4.9,
    reviewCount: 9,
    sellerId: "seller-3",
    seller: mockSellers[2],
    createdAt: "2024-10-15",
    updatedAt: "2024-10-15",
    isApproved: true,
  },
  {
    id: "prod-8",
    name: "Focusrite Scarlett 2i2 3rd Gen Audio Interface",
    slug: "focusrite-scarlett-2i2-3rd-gen",
    category: "Studio Gear",
    brand: "Focusrite",
    model: "Scarlett 2i2",
    price: 18500,
    condition: "new",
    quantity: 12,
    location: "Mumbai, MH",
    description: "The world's best selling audio interface. Two mic/line/instrument inputs, Air mode, 24-bit/192kHz, USB-C.",
    specifications: {
      "Inputs": "2 Combo XLR/TRS",
      "Outputs": "2 Balanced TRS",
      "Resolution": "24-bit/192kHz",
      "Connectivity": "USB-C",
      "Phantom": "48V",
      "Latency": "2.74ms"
    },
    images: ["https://images.unsplash.com/photo-1598488035139-bdbb22374218?w=800"],
    rating: 4.8,
    reviewCount: 112,
    sellerId: "seller-2",
    seller: mockSellers[1],
    createdAt: "2024-10-10",
    updatedAt: "2024-10-10",
    isApproved: true,
    isFeatured: true,
  },
  {
    id: "prod-9",
    name: "Yamaha YAS-280 Alto Saxophone",
    slug: "yamaha-yas-280-alto-saxophone",
    category: "Wind Instruments",
    brand: "Yamaha",
    model: "YAS-280",
    price: 98000,
    condition: "new",
    quantity: 2,
    location: "Chennai, TN",
    description: "Student alto saxophone with excellent intonation and playability. Gold lacquer finish, high F# and front F keys.",
    specifications: {
      "Key": "Eb",
      "Finish": "Gold Lacquer",
      "Keys": "High F#, Front F",
      "Mouthpiece": "4C included",
      "Case": "Included"
    },
    images: ["https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800"],
    rating: 4.7,
    reviewCount: 15,
    sellerId: "seller-3",
    seller: mockSellers[2],
    createdAt: "2024-10-05",
    updatedAt: "2024-10-05",
    isApproved: true,
  },
  {
    id: "prod-10",
    name: "Ernie Ball Regular Slinky Strings - 3 Pack",
    slug: "ernie-ball-regular-slinky-3-pack",
    category: "Accessories",
    brand: "Ernie Ball",
    model: "2221",
    price: 1650,
    condition: "new",
    quantity: 100,
    location: "Bangalore, KA",
    description: "World's most popular electric guitar strings. Nickel wound, 10-46 gauge. 3 pack value.",
    specifications: {
      "Gauge": "10-13-17-26-36-46",
      "Material": "Nickel Wound",
      "Quantity": "3 Sets",
      "Type": "Electric Guitar"
    },
    images: ["https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800"],
    rating: 4.9,
    reviewCount: 245,
    sellerId: "seller-1",
    seller: mockSellers[0],
    createdAt: "2024-10-01",
    updatedAt: "2024-10-01",
    isApproved: true,
  },
]

export const mockReviews: Review[] = [
  {
    id: "rev-1",
    productId: "prod-1",
    userId: "user-1",
    user: { id: "user-1", email: "buyer@example.com", name: "Amit Sharma", role: "buyer", createdAt: "2023-01-01" },
    rating: 5,
    comment: "Absolutely love this Strat! Setup was perfect, plays like butter. Rajesh was super helpful with shipping.",
    createdAt: "2024-11-12"
  },
  {
    id: "rev-2",
    productId: "prod-1",
    userId: "user-2",
    user: { id: "user-2", email: "buyer2@example.com", name: "Priya Nair", role: "buyer", createdAt: "2023-02-01" },
    rating: 4,
    comment: "Great guitar, tone is amazing. Slight fret buzz on high E but manageable.",
    createdAt: "2024-11-11"
  }
]

export const mockUsers: User[] = [
  { id: "buyer-1", email: "buyer@example.com", name: "Test Buyer", role: "buyer", createdAt: "2023-01-01", location: "Hyderabad, TS" },
  { id: "seller-1", email: "raj.guitars@example.com", name: "Rajesh Kumar", role: "seller", createdAt: "2023-01-15", verified: true },
  { id: "admin-1", email: "admin@tunemart.com", name: "Admin User", role: "admin", createdAt: "2022-01-01" },
]

export function getProductById(id: string) {
  return mockProducts.find(p => p.id === id || p.slug === id)
}

export function getProductsByCategory(category: ProductCategory) {
  return mockProducts.filter(p => p.category === category)
}

export function searchProducts(query: string) {
  const q = query.toLowerCase()
  return mockProducts.filter(p => 
    p.name.toLowerCase().includes(q) ||
    p.brand.toLowerCase().includes(q) ||
    p.model.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q)
  )
}
